version: "3.8"
services:
  backend:
    image: "mwmuriithi/springboot-react-fullstack:5.2.2022.15.22.34"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev

