spring:
  application:
    name: Spring React Application
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  datasource:
    jdbc-url: jdbc:postgresql://aa12vci0azb96wt.c30mxocki8ma.af-south-1.rds.amazonaws.com:5432/springreact
    username: tenabotreq
    password: password
    pool-size: 30

server:
  error:
    include-message: always
    include-binding-errors: always